language: r
cache: packages
sudo: true
r_packages:
  - covr
  - devtools
after_success:
  - Rscript -e 'library(covr);codecov()'
before_install:
  - Rscript -e 'install.packages("BiocManager")'
  - Rscript -e 'BiocManager::install("BEclear", version = "3.9")'
