language: r
r:
  - devel
  - bioc-devel
cache: packages
sudo: true
r_packages:
  - covr
  - devtools
before_install:
  - Rscript -e 'install.packages("BiocManager")'
  - Rscript -e 'BiocManager::install("BEclear", version = "3.9")'
after_success:
  - Rscript -e 'library(covr);codecov()'

